/**
 * Motion Titles CDN Worker
 *
 * Validates HMAC-signed URLs and serves assets from Cloudflare R2.
 *
 * URL format (generated by backend `signCdnUrl()`):
 *   https://cdn.kendyproducoes.com/<key>?fp=<fingerprint>&e=<expires>&s=<sig>
 *
 * Signature data: `${key}\n${fingerprint}\n${expires}` HMAC-SHA256 base64url
 * Secret shared with backend via env var CDN_SIGN_SECRET.
 *
 * Routes:
 *   GET  /<key>          → validate sig + serve from R2 (private assets, mogrt)
 *   GET  /public/<key>   → serve directly from R2 (previews .mp4, thumbnails)
 *   GET  /health         → 200 OK (uptime check)
 *
 * Bindings required (wrangler.toml):
 *   - R2 bucket    : ASSETS
 *   - Env secrets  : CDN_SIGN_SECRET
 */

const STREAM_HEADERS = {
    "Cache-Control": "private, max-age=3600",
    "Cross-Origin-Resource-Policy": "cross-origin",
};

const PUBLIC_CACHE_HEADERS = {
    "Cache-Control": "public, max-age=86400",
    "Cross-Origin-Resource-Policy": "cross-origin",
};

function b64urlToBuf(s) {
    s = s.replace(/-/g, "+").replace(/_/g, "/");
    while (s.length % 4) s += "=";
    return Uint8Array.from(atob(s), c => c.charCodeAt(0));
}

async function hmacVerify(secret, data, signatureB64Url) {
    const key = await crypto.subtle.importKey(
        "raw",
        new TextEncoder().encode(secret),
        { name: "HMAC", hash: "SHA-256" },
        false,
        ["verify"]
    );
    return crypto.subtle.verify(
        "HMAC",
        key,
        b64urlToBuf(signatureB64Url),
        new TextEncoder().encode(data)
    );
}

function contentType(key) {
    const k = key.toLowerCase();
    if (k.endsWith(".mogrt")) return "application/octet-stream";
    if (k.endsWith(".mp4"))   return "video/mp4";
    if (k.endsWith(".webm"))  return "video/webm";
    if (k.endsWith(".jpg") || k.endsWith(".jpeg")) return "image/jpeg";
    if (k.endsWith(".png"))   return "image/png";
    if (k.endsWith(".json"))  return "application/json";
    return "application/octet-stream";
}

async function serveFromR2(bucket, key, headers) {
    const obj = await bucket.get(key);
    if (!obj) return new Response("not_found", { status: 404 });
    const respHeaders = new Headers(headers);
    respHeaders.set("Content-Type", contentType(key));
    if (obj.size != null)  respHeaders.set("Content-Length", String(obj.size));
    if (obj.etag)          respHeaders.set("ETag", obj.etag);
    if (obj.httpEtag)      respHeaders.set("ETag", obj.httpEtag);
    return new Response(obj.body, { status: 200, headers: respHeaders });
}

export default {
    async fetch(request, env, ctx) {
        const url = new URL(request.url);
        const pathname = decodeURIComponent(url.pathname);

        // ---- health ----
        if (pathname === "/health") {
            return Response.json({ ok: true, service: "Motion Titles-cdn", time: new Date().toISOString() });
        }

        // ---- CORS preflight ----
        if (request.method === "OPTIONS") {
            return new Response(null, {
                status: 204,
                headers: {
                    "Access-Control-Allow-Origin": "*",
                    "Access-Control-Allow-Methods": "GET, OPTIONS",
                    "Access-Control-Allow-Headers": "Range, If-None-Match",
                    "Access-Control-Max-Age": "86400",
                },
            });
        }

        if (request.method !== "GET") {
            return new Response("method_not_allowed", { status: 405 });
        }

        // ---- /public/* → unsigned (previews, thumbnails) ----
        if (pathname.startsWith("/public/")) {
            const key = pathname.slice("/public/".length);
            if (!key) return new Response("missing_key", { status: 400 });
            return serveFromR2(env.ASSETS, key, PUBLIC_CACHE_HEADERS);
        }

        // ---- /<key> → signed (mogrt, paid assets) ----
        const key = pathname.replace(/^\/+/, "");
        if (!key) return new Response("missing_key", { status: 400 });

        const fp  = url.searchParams.get("fp");
        const exp = url.searchParams.get("e");
        const sig = url.searchParams.get("s");
        if (!fp || !exp || !sig) {
            return new Response("missing_signature_params", { status: 401 });
        }

        const now = Math.floor(Date.now() / 1000);
        const expNum = parseInt(exp, 10);
        if (!Number.isFinite(expNum) || expNum < now) {
            return new Response("expired", { status: 401 });
        }

        const data = `${key}\n${fp}\n${expNum}`;
        const ok = await hmacVerify(env.CDN_SIGN_SECRET, data, sig);
        if (!ok) {
            return new Response("invalid_signature", { status: 401 });
        }

        return serveFromR2(env.ASSETS, key, STREAM_HEADERS);
    },
};
